## Configuration for the STARsolo_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################

# Sample sheet requires a sampleID, and locations of fastqs for R1 and R2
#     For multi-lane inputs, use the following format (from STARsolo github page):
#       --readFilesIn Read2_Lane1.fastq.gz,Read2_Lane2.fastq.gz,Read2_Lane3.fastq.gz  Read1_Lane1.fastq.gz,Read1_Lane2.fastq.gz,Read1_Lane3.fastq.gz

## ~~~~~ sample sheets ~~~~~
# SAMPLE_SHEET_PATH: /home/dwm269/private_utils/sample_sheets/slideseq_rnd1-sample_sheet.csv
# SAMPLE_SHEET_PATH: /home/dwm269/private_utils/sample_sheets/SS_LKO_Rnd1-sample_sheet.csv
# SAMPLE_SHEET_PATH: /home/dwm269/private_utils/sample_sheets/STRSHD_Rnd2-sample_sheet.csv
SAMPLE_SHEET_PATH: /home/dwm269/private_utils/sample_sheets/SS_cohen_testes.csv
# SAMPLE_SHEET_PATH: /home/dwm269/private_utils/sample_sheets/ChickenSurgerySlideSeq-sample_sheet.csv


# STARsolo parameters
CORES: 39 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 500000000000 # limit in bytes

## Chemistry details (whitelists, barcode/UMI design, etc.)
CHEMISTRY_SHEET: resources/chemistry_sheet.csv

########################################################################################################
# Important directory file paths
########################################################################################################
# TMPDIR: /workdir/dwm269/totalRNA/tmp # directory for temporary files

# TMPDIR: /workdir/dwm269/spatial_lmna/tmp
# OUTDIR: /workdir/dwm269/spatial_lmna/data/align_out

# TMPDIR: /workdir/dwm269/totalRNA/STRS-HD/tmp
# OUTDIR: /workdir/dwm269/totalRNA/STRS-HD/data/align_out

# TMPDIR: /workdir/dwm269/butcher_surgery/tmp
# OUTDIR: /workdir/dwm269/butcher_surgery/data/align_out

TMPDIR: /workdir/dwm269/cohen_testes/tmp
OUTDIR: /workdir/dwm269/cohen_testes/data/align_out

########################################################################################################
# Executables - file paths
########################################################################################################
STAR_EXEC: /programs/STAR-2.7.10a/STAR # v2.7.10a /programs/STAR/STAR
KALLISTO_EXEC: kallisto
BUST_EXEC: bustools
CUTADAPT_EXEC: cutadapt
TRIMGALORE_EXEC: /home/dwm269/usr/bin/TrimGalore-0.6.6/trim_galore
FASTQC_EXEC: fastqc
SAMTOOLS_EXEC: samtools
UMITOOLS_EXEC: umi_tools
QUALIMAP_EXEC: qualimap
BAM2SPLITBW: /home/dwm269/DWM_utils/seq_utils/bam2splitBigWig.sh #Custom function in DWM_utils that splits a bam file by strand and converts it into bigwig format
FASTX_COLLAPSER: fastx_collapser
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored
PICARD_EXEC: /home/dwm269/miniconda3/envs/STARsolo/share/picard-2.26.10-0/picard.jar

########################################################################################################
# Resources - file paths
########################################################################################################
FASTQC_ADAPTERS: /home/dwm269/DWM_utils/align_pipes/curio_STARsolo/resources/fastqc_adapters.txt

### Mouse ###
# STAR_REF: /workdir/dwm269/genomes/mm39_all/STAR_GRCm39_GENCODEM28 # path to STAR-formatted reference genome
# GENES_GTF: /workdir/dwm269/genomes/mm39_all/GENCODE_M28/gencode.vM28.chr_patch_hapl_scaff.annotation.gtf
# STAR_MIRBASE_REF: /workdir/dwm269/genomes/mm39_all/STAR_mirbase_mirge
# SPECIES: mouse # species passed to mirge3.0
# MIRGE_LIB: /home/dwm269/usr/bin/miRge3_Lib
