# slurm_config.yml - cluster configuration
__default__:
    job-name: slide_snake
    partition: pe2
    time: 1:00:00 
    nodes: 1
    threads: 1
    mem: 8G
    output: .slurm/%j.log
    chdir: /gpfs/commons/groups/innovation/dwm/slide_snake

# rule-specific
# rules/short_read/ ~~~~~~~~~~~~~
## 1a_mergefqs.smk
merge_fastqs:
    threads: 1
    mem: 16G

## 1b_trimming.smk
cutadapt:
    threads: 8
    mem: 16G

cutadapt2:
    threads: 8
    mem: 16G

R1_hardTrimming:
    threads: 24
    mem: 16G

R1_internalTrimming:
    threads: 24
    mem: 16G

## 1c_fastqc.smk
fastQC_preTrim:
    threads: 24
    mem: 16G

fastQC_postTrim:
    threads: 24
    mem: 16G

fastQC_twiceTrim:
    threads: 24
    mem: 16G

## 2a_rRNA_bwa.smk
bwa_rRNA_align:
    threads: 16
    time: 2:00:00
    mem: 96G

bwa_rRNA_filter_R1:
    mem: 64G


## 2b_rRNA_STAR.smk
STAR_rRNA_align:
    threads: 16
    time: 2:00:00
    mem_mb: 256000

STAR_rRNA_compress_outs:
    threads: 16

STAR_rRNA_rename_compress_unmapped:
    threads: 16
    
STAR_rRNA_filtered_fastqc:
    threads: 16
    
## 2c_rRNA_qualimap.smk
qualimapQC_rRNA_bwa:
    mem: 32G

qualimapQC_rRNA_STAR:
    mem: 32G

qualimap_summary2csv_rRNA_STAR:
    mem: 4G

## 2d_ribodetector.smk
ribodetector:
    threads: 16
    mem: 16G

ribodetector_get_noRibo_list:
    threads: 1
    mem: 4G

ribodetector_gunzip_R1:
    threads: 1
    mem: 4G

ribodetector_filter_R1:
    mem: 32G

ribodetector_filter_R1_internalTrim:
    mem: 32G

ribodetector_filter_R1_hardTrim:
    mem: 32G

ribodetector_gunzip_R1:
    threads: 24
    mem: 8G

## 3a_star_align.smk
STARsolo_align:
    threads: 16
    time: 2:00:00
    mem: 256G
    mem_mb: 256000

## 3b_star_unmapped.smk

## 3c_star_dedup.smk

## 3d_star_qualimap.smk
qualimapQC_STAR:
    mem: 32G

# 4 ~~~~~~~~~~~~~~~
kbpython_std:
    threads: 16
    time: 2:00:00
    mem: 256G
    mem_mb: 256000

# 5 ~~~~~~~~~~~~~~~    
miRge3_pseudobulk:
    threads: 16
    time: 2:00:00
    mem: 256G
    mem_mb: 256000
    
# 6 ~~~~~~~~~~~~~~~
cache_preQC_h5ad_STAR:
    mem: 32G

# rules/ont/ ~~~~~~~~~~~~~
## 1a_preprocessing.smk
ont_call_adapter_scan:
    mem: 16G

ont_readIDs_by_adapter_type:
    threads: 24
    mem: 16G

ont_adapterScan_QC:
    threads: 1
    mem: 8G

ont_merge_scan_lists:
    threads: 1
    mem: 16G

ont_subset_fastq_by_adapter_type:
    threads: 24
    mem: 16G

ont_split_fastq_to_R1_R2:
    threads: 16
    mem: 8G

## 1b_trimming.smk
ont_cutadapt:
    threads: 24
    mem: 16G

ont_R1_hardTrimming:
    threads: 24
    mem: 16G
    
ont_R1_internalTrim:
    threads: 24
    mem: 16G

ont_cutadapt_internalTrimming:
    threads: 24
    mem: 16G

## 1c_barcode_calling.smk
ont_fastq_call_bc_from_adapter:
    threads: 1
    mem: 32G

ont_tsv_bc_correction:
    threads: 24
    mem: 32G


## 1d_minimap2.smk
ont_align_minimap2_genome:
    threads: 16
    time: 2:00:00
    mem: 128G

ont_sort_compress_output:
    mem: 16G
    threads: 1


ont_featureCounts:
    mem: 32G
    threads: 1

ont_add_featureCounts_to_bam:
    mem: 16G
    threads: 1

ont_add_corrected_barcodes:
    mem: 16G
    threads: 1

ont_add_umis:
    mem: 16G
    threads: 1

ont_filter_bam_empty_tags:
    mem: 16G
    threads: 1

ont_umitools_count:
    mem: 16G
    threads: 1

ont_counts_to_sparse:
    mem: 16G
    threads: 1


## 1d_STAR.smk
ont_STARsolo_align:
    threads: 16
    time: 2:00:00
    mem: 128G
    mem_mb: 128000


## 2_qualimap.smk
ont_qualimap_minimap2:
    mem: 32G
    threads: 1

ont_qualimap_STAR:
    mem: 32G
    threads: 1

ont_qualimap_summary2csv:
    mem: 8G
    threads: 1

## 2_read_qc.smk
ont_readQC_preCutadapt:
    mem: 8G
    threads: 16

ont_readQC_postCutadapt:
    mem: 8G
    threads: 16

ont_readQC_bam:
    mem: 8G
    threads: 1

readQC_downsample:
    mem: 4G
    threads: 1

ont_readQC_summaryplot:
    mem: 8G